---
title: "AMMONIUM CHLORIDE"
format: html
---

[← Back to Chemical Safety](../chemical-safety.qmd)


## Basic information
- Chemical formula(s): ${\rm NH_4Cl}$
- Other names: sal ammoniac
- CAS: 12125-02-9
- International Chemical Safety Card (ICSC): [1051](https://inchem.org/documents/icsc/icsc/eics1051.htm)
- Flammability: no
- [NOAA's](https://cameochemicals.noaa.gov/chemical/2422) description: white crystalline solid, soluble in water, immediate steps should be taken to limit its spread to the environment

## NFPA 704 (fire diamond)
- **Health (blue): 2** - intense or continued but not chronic exposure could cause temporary incapacitation or possible residual injury.
- **Flammability (red): 0** - will not burn under typical fire conditions, will not burn in air unless exposed to a temperature of 820 °C for more than 5 minutes.
- **Instability–reactivity (yellow): 0** - normally stable, even under fire exposure conditions, and is not reactive with water.
- **Special notice (white): -**

## Hazard statements
| Code | Phrase                        |
| ---- | ----------------------------- |
| H302 | harmful if swallowed          |
| H319 | causes serious eye irritation |

## Precautionary statements
| Code           | Phrase                                                                                                                           |
| -------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| P305+P351+P338 | IF IN EYES: rinse continuously with water for several minutes, remove contact lenses if present and easy to do, continue rinsing |

## Protective measures

### Gloves
[Occupational Safety and Health Act of 1970](https://www.osha.gov/sites/default/files/publications/osha3151.pdf) and [OSHA Glove Selection Chart](https://safety.fsu.edu/safety_manual/OSHA%20Glove%20Selection%20Chart.pdf) do not provide recommendation on gloves for handling ammonium chloride. [Gloves4U](https://www.gloves4u.eu/x/Chemical%20Resistant%20Chart%20-%20final%20(5).pdf) categorizes gloves into four protection levels (excellent, good, fair, poor) for given chemical. The levels of protection against ammonium chloride for four types of gloves are:

- Neoprene: N/A.
- Natural latex or rubber: **excellent**.
- Buthyl: N/A.
- Nitrile: **good**.

### Safety goggles
- Always wear safety goggles when handling ammonium chloride. Corrective glasses are not considered safety googles.
- Handle ammonium chloride inside the fume hood only (with exception of moving the closed bottle to and from the storage cabinet).

### Clothing
- Wear long trousers and fully covered shoes.
- Contact lenses are forbidden while working with chemical substances, even in combination with safety glasses.
- Do not wear cosmetics.
- Do not wear synthetic clothing while working with flammable liquids or gases or when a hazard is present as these materials tend to melt and stick to exposed skin.
- Do not wear headphones.

## Spill management
- Use personal protective equipment.
- Avoid dust formation, avoid breathing dust.
- Avoid breathing vapors or mist.
- Ensure adequate ventilation.
- Evacuate personnel to safe areas.
- Sweep up without creating dust and arrange disposal.
- Do not let it enter drain.
- If a spill happened outside the fume hood (on the floor or desktop) contact Dr Jakub Tkaczuk (+41 44 632 31 62) and the ETH Emergency Desk (+41 44 342 11 88 from mobile or 888 from landline).

[Back to chemical safety page](https://github.com/Global-Health-Engineering/group-safety/tree/main/02-chemical-safety)  
