---
title: "AMMONIUM HYDROXIDE 01-035"
format: html
---

[← Back to Chemical Safety](../chemical-safety.qmd)


## Basic information
- Chemical formula(s): ${\rm NH_3(aq)}$
- Other names: aqua ammonia, ammonium hydrate, ammonia aqueous solution (10-35%) 
- CAS: 1336-21-6
- International Chemical Safety Card (ICSC): [0215](https://inchem.org/documents/icsc/icsc/eics0215.htm)
- Flammability: **yes - requires considerable preheating**
- [NOAA's](https://cameochemicals.noaa.gov/chemical/2434) description: clear colouress liquid consisting, corrosive to tissue and metals. Although ammonia is lighter than air, the vapours from a leak will initially hug the ground

## NFPA 704 (fire diamond)
- **Health (blue): 3** - short exposure could cause serious temporary or moderate residual injury.
- **Flammability (red): 1** - requires considerable preheating, under all ambient temperature conditions, before ignition and combustion can occur. Flash point above 93.3 °C.
- **Instability–reactivity (yellow): 0** - normally stable, even under fire exposure conditions, and is not reactive with water.
- **Special notice (white):**
	- **COR** - corrosive, strong base.

## Hazard statements
| Code | Phrase                                               |
| ---- | ---------------------------------------------------- |
| H302 | harmful if swallowed                                 |
| H314 | causes severe skin burns and eye damage              |
| H335 | may cause respiratory irritation                     |
| H410 | very toxic to aquatic life with long lasting effects |

## Precautionary statements
| Code           | Phrase                                                                                                       |
| -------------- | ------------------------------------------------------------------------------------------------------------ |
| P261           | avoid breathing dust/fume/gas/mist/vapours/spray                                                             |
| P271           | use only outdoors or in a well-ventilated area                                                               |
| P273           | avoid release to the environment                                                                             |
| P280           | wear protective gloves/protective clothing/eye protection/face protection                                    |
| P303+P361+P353 | IF ON SKIN (or hair): remove/take off immediately all contaminated clothing, rinse skin with water or shower |
| P305+P351+P338 | IF IN EYES: rinse continuously with water for several minutes, remove contact lenses if present and easy to do, continue rinsing |

## Protective measures

### Gloves
[Occupational Safety and Health Act of 1970](https://www.osha.gov/sites/default/files/publications/osha3151.pdf) and [OSHA Glove Selection Chart](https://safety.fsu.edu/safety_manual/OSHA%20Glove%20Selection%20Chart.pdf) categorize gloves into four protection levels (very good, good, fair, poor (not recommended)) for given chemical. The levels of protection against 10% - 35% solution of ammonium hydroxide for four types of gloves are:

- Neoprene: **very good**.
- Natural latex or rubber: **very good**.
- Buthyl: **very good**.
- Nitrile: **very good**.

### Safety goggles
- Always wear safety goggles when handling ammonium hydroxide. Corrective glasses are not considered safety googles.
- Handle ammonium hydroxide inside the fume hood only (with exception of moving the closed bottle to and from the storage cabinet).

### Clothing
- Wear long trousers and fully covered shoes.
- Contact lenses are forbidden while working with chemical substances, even in combination with safety glasses.
- Do not wear cosmetics.
- Do not wear synthetic clothing while working with flammable liquids or gases or when a hazard is present as these materials tend to melt and stick to exposed skin.
- Do not wear headphones.

## Spill management
- Use personal protective equipment.
- Avoid breathing vapors or mist.
- Ensure adequate ventilation.
- Evacuate personnel to safe areas.
- Arrange disposal.
- Do not let it enter drain.
- If a spill happened outside the fume hood (on the floor or desktop) contact Dr Jakub Tkaczuk (+41 44 632 31 62) and the ETH Emergency Desk (+41 44 342 11 88 from mobile or 888 from landline).

[Back to chemical safety page](https://github.com/Global-Health-Engineering/group-safety/tree/main/02-chemical-safety)  
