---
title: "BENZOPHENONE"
format: html
---

[← Back to Chemical Safety](../chemical-safety.qmd)


## Basic information
- Chemical formula(s): ${\rm (C_6H_5)_{2}CO}$, ${\rm Ph_2CO}$, ${\rm C_{13}H_{10}O}$
- Other names: diphenyl ketone, benzoylbenzene, phenyl ketone, diphenylmethanone
- CAS: 119-61-9
- International Chemical Safety Card (ICSC): [0389](https://www.inchem.org/documents/icsc/icsc/eics0389.htm)
- Flammability: **yes - requires considerable preheating**
- [NOAA's](https://cameochemicals.noaa.gov/chemical/8315) description: white solid with a flowery odour; may float or sink in water

## NFPA 704 (fire diamond)
- **Health (blue): 1** - exposure would cause irritation with only minor residual injury.
- **Flammability (red): 1** - requires considerable preheating, under all ambient temperature conditions, before ignition and combustion can occur.
- **Instability–reactivity (yellow): 0** - normally stable, even under fire exposure conditions, and is not reactive with water.
- **Special notice (white): -**

## Hazard statements
| Code | Phrase                                                            |
| ---- | ----------------------------------------------------------------- |
| H373 | may cause damage to organs through prolonged or repeated exposure |
| H411 | toxic to aquatic life with long lasting effects                   |

## Precautionary statements
| Code | Phrase                                                                    |
| ---- | ------------------------------------------------------------------------- |
| P260 | do not breathe dust/fume/gas/mist/vapours/spray                           |
| P273 | avoid release to the environment                                          |
| P314 | get medical advice/attention if you feel unwell                           |
| P391 | collect spillage                                                          |
| P501 | dispose of contents/container to [HCI-Shop](https://hci-shop.ethz.ch/en/) |

## Protective measures

### Gloves
[Occupational Safety and Health Act of 1970](https://www.osha.gov/sites/default/files/publications/osha3151.pdf) and [OSHA Glove Selection Chart](https://safety.fsu.edu/safety_manual/OSHA%20Glove%20Selection%20Chart.pdf) do not provide recommendation on gloves for handling benzophenone. [Apollo Scientific](https://store.apolloscientific.co.uk/storage/msds/OR8243_msds.pdf) provides the following recommendations:

- Neoprene: N/A
- Natural latex or rubber: N/A
- Buthyl: **good at thickness greater than 0.35 mm**.
- Nitrile: **good at thickness greater than 0.35 mm**.

### Safety goggles
- Always wear safety goggles when handling benzophenone. Corrective glasses are not considered safety googles.
- Handle benzophenone inside the fume hood only (with exception of moving the closed bottle to and from the storage cabinet).

### Clothing
- Wear long trousers and fully covered shoes.
- Contact lenses are forbidden while working with chemical substances, even in combination with safety glasses.
- Do not wear cosmetics.
- Do not wear synthetic clothing while working with flammable liquids or gases or when a hazard is present as these materials tend to melt and stick to exposed skin.
- Do not wear headphones.

## Spill management
- Use personal protective equipment.
- Avoid dust formation, avoid breathing dust.
- Avoid breathing vapors or mist.
- Ensure adequate ventilation.
- Evacuate personnel to safe areas.
- Sweep up without creating dust and arrange disposal.
- Do not let it enter drain.
- If a spill happened outside the fume hood (on the floor or desktop) contact Dr Jakub Tkaczuk (+41 44 632 31 62) and the ETH Emergency Desk (+41 44 342 11 88 from mobile or 888 from landline).

[Back to chemical safety page](https://github.com/Global-Health-Engineering/group-safety/tree/main/02-chemical-safety)  
