---
title: "IRON III CHLORIDE ANHYDROUS"
format: html
---

[← Back to Chemical Safety](../chemical-safety.qmd)


## Basic information
- Chemical formula(s): ${\rm FeCl_3}$
- Other names: ferric chloride anhydrous, Iron trichloride, flores martis, molysite
- CAS: 7705-08-0
- International Chemical Safety Card (ICSC): [1499](https://inchem.org/documents/icsc/icsc/eics1499.htm)
- Flammability: no
- [NOAA's](https://cameochemicals.noaa.gov/chemical/8680) description: orange to brown-black solid, slightly soluble in water; corrosive to aluminium and most metals, when wet

## NFPA 704 (fire diamond)
- **Health (blue): 2** - intense or continued but not chronic exposure could cause temporary incapacitation or possible residual injury.
- **Flammability (red): 0** - will not burn under typical fire conditions, will not burn in air unless exposed to a temperature of 820 °C for more than 5 minutes.
- **Instability–reactivity (yellow): 0** - normally stable, even under fire exposure conditions, and is not reactive with water.
- **Special notice (white): -**

## Hazard statements
| Code | Phrase                                  |
| ---- | --------------------------------------- |
| H290 | may be corrosive to metals              |
| H302 | harmful if swallowed                    |
| H314 | causes severe skin burns and eye damage |

## Precautionary statements
| Code           | Phrase                                                                                                                           |
| -------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| P234           | keep only in original container/packaging                                                                                        |
| P260           | do not breathe dust/fume/gas/mist/vapours/spray                                                                                  |
| P264           | wash ... thoroughly after handling                                                                                               |
| P270           | do not eat, drink or smoke when using this product                                                                               |
| P273           | avoid release to the environment                                                                                                 |
| P280           | wear protective gloves/protective clothing/eye protection/face protection                                                        |
| P301+P312      | IF SWALLOWED: call the ETH Emergency Desk: +41 44 342 11 88 (from mobile) or 888 (from landline)                                 |
| P301+P330+P331 | IF SWALLOWED: rinse mouth, do NOT induce vomiting                                                                                |
| P303+P361+P353 | IF ON SKIN (or hair): remove/take off immediately all contaminated clothing, rinse skin with water or shower                     |
| P304+P340      | IF INHALED: remove victim to fresh air and keep at rest in a position comfortable for breathing                                  |
| P305+P351+P338 | IF IN EYES: rinse continuously with water for several minutes, remove contact lenses if present and easy to do, continue rinsing |
| P310           | immediately call the ETH Emergency Desk: +41 44 342 11 88 (from mobile) or 888 (from landline)                                   |
| P321           | specific treatment (see the label)                                                                                               |
| P363           | wash contaminated clothing before reuse                                                                                          |
| P390           | absorb spillage to prevent material damage                                                                                       |
| P405           | store locked up                                                                                                                  |
| P406           | store in a corrosive resistant container with a resistant inner liner                                                            |
| P501           | dispose of contents/container to [HCI-Shop](https://hci-shop.ethz.ch/en/)                                                        |

## Protective measures

### Gloves
[Occupational Safety and Health Act of 1970](https://www.osha.gov/sites/default/files/publications/osha3151.pdf) and [OSHA Glove Selection Chart](https://safety.fsu.edu/safety_manual/OSHA%20Glove%20Selection%20Chart.pdf) do not provide recommendation on gloves for handling iron(III) chloride. [Augusta University](https://www.augusta.edu/services/ehs/chemsafe/PDF%20files/gloveselechart.pdf) categorizes gloves into four protection levels (excellent, good, fair, not recommended) for given chemical. The levels of protection against iron(III) chloride for four types of gloves are:

- Neoprene: **excellent**.
- Natural latex or rubber: **excellent**.
- Buthyl: **excellent**.
- Nitrile: **excellent**.

### Safety goggles
- Always wear safety goggles when handling anhydrous iron(III) chloride. Corrective glasses are not considered safety googles.
- Handle anhydrous iron(III) chloride inside the fume hood only (with exception of moving the closed bottle to and from the storage cabinet).

### Clothing
- Wear long trousers and fully covered shoes.
- Contact lenses are forbidden while working with chemical substances, even in combination with safety glasses.
- Do not wear cosmetics.
- Do not wear synthetic clothing while working with flammable liquids or gases or when a hazard is present as these materials tend to melt and stick to exposed skin.
- Do not wear headphones.

## Spill management
- Use personal protective equipment.
- Avoid dust formation, avoid breathing dust.
- Avoid breathing vapors or mist.
- Ensure adequate ventilation.
- Evacuate personnel to safe areas.
- Sweep up without creating dust and arrange disposal.
- Do not let it enter drain.
- If a spill happened outside the fume hood (on the floor or desktop) contact Dr Jakub Tkaczuk (+41 44 632 31 62) and the ETH Emergency Desk (+41 44 342 11 88 from mobile or 888 from landline).

[Back to chemical safety page](https://github.com/Global-Health-Engineering/group-safety/tree/main/02-chemical-safety)  
