---
title: "METHYL SALICYLATE"
format: html
---

[← Back to Chemical Safety](../chemical-safety.qmd)


## Basic information
- Chemical formula(s): ${\rm C_8H_8O_3}$
- Other names: methyl hydroxybenzoate
- CAS: 119-36-8
- International Chemical Safety Card (ICSC): N/A (see [NOAA safety data sheet](https://cameochemicals.noaa.gov/chemical/17825))
 - Flammability: **yes - requires considerable preheating**
- [NOAA's](https://cameochemicals.noaa.gov/chemical/17825) description: colourless, yellowish or reddish liquid with odour of wintergreen

## NFPA 704 (fire diamond)
- **Health (blue): 2** - intense or continued but not chronic exposure could cause temporary incapacitation or possible residual injury.
- **Flammability (red): 1** - requires considerable preheating, under all ambient temperature conditions, before ignition and combustion can occur. Flash point above 93.3 °C.
- **Instability–reactivity (yellow): 0** - normally stable, even under fire exposure conditions, and is not reactive with water.
- **Special notice (white): -**

## Hazard statements
| Code | Phrase               |
| ---- | -------------------- |
| H302 | harmful if swallowed |

## Precautionary statements
| Code           | Phrase                                                                                                                           |
| -------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| P264           | wash ... thoroughly after handling                                                                                               |
| P270           | do not eat, drink or smoke when using this product                                                                               |
| P280           | wear protective gloves/protective clothing/eye protection/face protection                                                        |
| P301+P312      | IF SWALLOWED: call the ETH Emergency Desk: +41 44 342 11 88 (from mobile) or 888 (from landline)                                 |
| P302+P352      | IF ON SKIN: wash with soap and water                                                                                             |
| P305+P351+P338 | IF IN EYES: rinse continuously with water for several minutes, remove contact lenses if present and easy to do, continue rinsing |
| P321           | specific treatment (see the label)                                                                                               |
| P330           | rinse mouth                                                                                                                      |
| P332+P313      | IF SKIN IRRITATION OCCURS: get medical advice/attention                                                                          |
| P337+P313      | IF EYE IRRITATION PERSISTS: get medical advice/attention                                                                         |
| P362           | take off contaminated clothing                                                                                                   |
| P501           | dispose of contents/container to [HCI-Shop](https://hci-shop.ethz.ch/en/)                                                        |

## Protective measures

### Gloves
[Occupational Safety and Health Act of 1970](https://www.osha.gov/sites/default/files/publications/osha3151.pdf) and [OSHA Glove Selection Chart](https://safety.fsu.edu/safety_manual/OSHA%20Glove%20Selection%20Chart.pdf) do not provide recommendation on gloves for handling methyl salicylate. [Becky](https://becky.ee/useful-articles/chemical-resistance-table-for-gloves/?lang=en), a PPE distributor, categorizes gloves into four protection levels (excellent, good, fair, not recommended) for given chemical. The levels of protection against methyl salicylate for four types of gloves are:

- Neoprene: **fair**.
- Natural latex or rubber: **fair**.
- Buthyl: N/A
- Nitrile: **good**.

### Safety goggles
- Always wear safety goggles when handling methyl salicylate. Corrective glasses are not considered safety googles.
- Handle methyl salicylate inside the fume hood only (with exception of moving the closed bottle to and from the storage cabinet).

### Clothing
- Wear long trousers and fully covered shoes.
- Contact lenses are forbidden while working with chemical substances, even in combination with safety glasses.
- Do not wear cosmetics.
- Do not wear synthetic clothing while working with flammable liquids or gases or when a hazard is present as these materials tend to melt and stick to exposed skin.
- Do not wear headphones.

## Spill management
- Use personal protective equipment.
- Avoid dust formation, avoid breathing dust.
- Avoid breathing vapors or mist.
- Ensure adequate ventilation.
- Evacuate personnel to safe areas.
- Sweep up without creating dust and arrange disposal.
- Do not let it enter drain.
- If a spill happened outside the fume hood (on the floor or desktop) contact Dr Jakub Tkaczuk (+41 44 632 31 62) and the ETH Emergency Desk (+41 44 342 11 88 from mobile or 888 from landline).

[Back to chemical safety page](https://github.com/Global-Health-Engineering/group-safety/tree/main/02-chemical-safety)  
