---
title: "246-TRICHLOROANISOLE"
format: html
---

[← Back to Chemical Safety](../chemical-safety.qmd)


## Basic information
- Chemical formula(s): ${\rm C_7H_5Cl_3O}$
- Other names: 1,3,5-trichloro-2-methoxybenzene, 2,4,6-trichloromethoxybenzene, TCA, tyrene
- CAS: 87-40-1
- International Chemical Safety Card (ICSC): N/A (see [Sigma Aldrich safety data sheet](https://www.sigmaaldrich.com/CH/en/sds/aldrich/235393))
- Flammability: 
- Description: 

## NFPA 704 (fire diamond)
- **Health (blue): 2** - intense or continued but not chronic exposure could cause temporary incapacitation or possible residual injury.
- **Flammability (red): 0** - will not burn under typical fire conditions, will not burn in air unless exposed to a temperature of 820 °C for more than 5 minutes.
- **Instability–reactivity (yellow): 0** - normally stable, even under fire exposure conditions, and is not reactive with water.
- **Special notice (white): -**

## Hazard statements
| Code | Phrase                                                 |
| ---- | ------------------------------------------------------ |
| H302 | harmful if swallowed                                   |
| H319 | causes serious eye irritation                          |
| H413 | may cause long lasting harmful effects to aquatic life |

## Precautionary statements
| Code           | Phrase                                                                                                                           |
| -------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| P264           | wash ... thoroughly after handling                                                                                               |
| P270           | do not eat, drink or smoke when using this product                                                                               |
| P273           | avoid release to the environment                                                                                                 |
| P280           | wear protective gloves/protective clothing/eye protection/face protection                                                        |
| P301+P312      | IF SWALLOWED: call the ETH Emergency Desk: +41 44 342 11 88 (from mobile) or 888 (from landline)                                 |
| P305+P351+P338 | IF IN EYES: rinse continuously with water for several minutes, remove contact lenses if present and easy to do, continue rinsing |
| P330           | rinse mouth                                                                                                                      |
| P337+P313      | IF EYE IRRITATION PERSISTS: get medical advice/attention                                                                         |
| P501           | dispose of contents/container to [HCI-Shop](https://hci-shop.ethz.ch/en/)                                                        |

## Protective measures

### Gloves
[Occupational Safety and Health Act of 1970](https://www.osha.gov/sites/default/files/publications/osha3151.pdf) and [OSHA Glove Selection Chart](https://safety.fsu.edu/safety_manual/OSHA%20Glove%20Selection%20Chart.pdf) do not provide recommendation on gloves for handling 2,4,6-trichloroanisole. [Sigma Aldrich](https://www.sigmaaldrich.com/CH/en/sds/aldrich/235393) provides the following information:

- Neoprene: N/A
- Natural latex or rubber: N/A
- Buthyl: N/A
- Nitrile: **very good protection;** 480 min breakthrough time for 0.11 mm thickness.

### Safety goggles
- Always wear safety goggles when handling 2,4,6-trichloroanisole. Corrective glasses are not considered safety googles.
- Handle 2,4,6-trichloroanisole inside the fume hood only (with exception of moving the closed bottle to and from the storage cabinet).

### Clothing
- Wear long trousers and fully covered shoes.
- Contact lenses are forbidden while working with chemical substances, even in combination with safety glasses.
- Do not wear cosmetics.
- Do not wear synthetic clothing while working with flammable liquids or gases or when a hazard is present as these materials tend to melt and stick to exposed skin.
- Do not wear headphones.

## Spill management
- Use personal protective equipment.
- Avoid dust formation, avoid breathing dust.
- Avoid breathing vapors or mist.
- Ensure adequate ventilation.
- Evacuate personnel to safe areas.
- Sweep up without creating dust and arrange disposal.
- Do not let it enter drain.
- If a spill happened outside the fume hood (on the floor or desktop) contact Dr Jakub Tkaczuk (+41 44 632 31 62) and the ETH Emergency Desk (+41 44 342 11 88 from mobile or 888 from landline).
