---
title: "CARBON DIOXIDE"
format: html
---

[← Back to Chemical Safety](../chemical-safety.qmd)


## Basic information
- Chemical formula(s): ${\rm CO_2}$
- Other names: carbonic acid gas, carbonic anhydride
- CAS: 124-38-9
- International Chemical Safety Card (ICSC): [0021](https://www.ilo.org/dyn/icsc/showcard.display?p_card_id=0021&p_version=2&p_lang=en)
- Flammability: no
- [NOAA's](https://cameochemicals.noaa.gov/chemical/330) description: colourless, odourless gas at atmospheric temperatures and pressures; relatively nontoxic and noncombustible; heavier than air and may asphyxiate by the displacement of air; soluble in water - forms carbonic acid, a mild acid; under prolonged exposure to heat or fire the container may rupture violently and rocket

## NFPA 704 (fire diamond)
- **Health (blue): 2** - intense or continued but not chronic exposure could cause temporary incapacitation or possible residual injury.
- **Flammability (red): 0** - will not burn under typical fire conditions, will not burn in air unless exposed to a temperature of 820 °C for more than 5 minutes.
- **Instability–reactivity (yellow): 0** - normally stable, even under fire exposure conditions, and is not reactive with water.
- **Special notice (white):**
	- **SA** - simple asphyxiant gas - a nontoxic or minimally toxic gas which reduces or displaces the normal oxygen concentration in breathing air.

## Hazard statements
| Code | Phrase                                              |
| ---- | --------------------------------------------------- |
| H280 | contains gas under pressure; may explode if heated  |

## Precautionary statements
| Code      | Phrase                                                  |
| --------- | ------------------------------------------------------- |
| P244      | keep valves and fittings free from oil and grease       |
| P403      | store in a well-ventilated place                        |

## Protective measures

### Gloves
No skin protection necessary.

### Safety goggles
- Always wear safety goggles when handling compressed gasses. Corrective glasses are not considered safety googles.

### Clothing
- Wear long trousers and fully covered shoes.
- Contact lenses are forbidden while working with chemical substances, even in combination with safety glasses.
- Do not wear cosmetics.
- Do not wear synthetic clothing while working with flammable liquids or gases or when a hazard is present as these materials tend to melt and stick to exposed skin.
- Do not wear headphones.

## Spill management
- If alarm triggers in the laboratory, the ${/rm CO_2}$ level might have risen above the safe value. Immediately leave the area and wait nearby for the emergency services to arrive.
