---
title: "CHLOROFORM"
format: html
---

[← Back to Chemical Safety](../chemical-safety.qmd)


## Basic information
- Chemical formula(s): ${\rm CHCl_3}$
- Other names: trichloromethane, methane trichloride, formyl trichloride
- CAS: 67-66-3
- International Chemical Safety Card (ICSC): [0027](https://inchem.org/documents/icsc/icsc/eics0027.htm)
- Flammability: no
- [NOAA's](https://cameochemicals.noaa.gov/chemical/2893) description: clear colourless liquid with a characteristic odour; denser than water and slightly soluble in water, hence sinks in water; nonflammable under most conditions, but burns under extreme conditions; may cause illness by inhalation, skin absorption or ingestion

## NFPA 704 (fire diamond)
- **Health (blue): 2** - intense or continued but not chronic exposure could cause temporary incapacitation or possible residual injury.
- **Flammability (red): 0** - will not burn under typical fire conditions, will not burn in air unless exposed to a temperature of 820 °C for more than 5 minutes.
- **Instability–reactivity (yellow): 0** - normally stable, even under fire exposure conditions, and is not reactive with water.
- **Special notice (white): -**

## Hazard statements
| Code  | Phrase                                                         |
| ----- | -------------------------------------------------------------- |
| H302  | harmful if swallowed                                           |
| H315  | causes skin irritation                                         |
| H319  | causes serious eye irritation                                  |
| H331  | toxic if inhaled                                               |
| H336  | may cause drowsiness or dizziness                              |
| H351  | suspected of causing cancer                                    |
| H361d | suspected of damaging the unborn child                         |
| H372  | causes damage to organs through prolonged or repeated exposure |

## Precautionary statements
| Code           | Phrase                                                                                                                           |
| -------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| P201           | obtain special instructions before use                                                                                           |
| P202           | do not handle until all safety precautions have been read and understood                                                         |
| P235           | keep cool                                                                                                                        |
| P260           | do not breathe dust/fume/gas/mist/vapours/spray                                                                                  |
| P264           | wash ... thoroughly after handling                                                                                               |
| P270           | do not eat, drink or smoke when using this product                                                                               |
| P271           | use only outdoors or in a well-ventilated area                                                                                   |
| P280           | wear protective gloves/protective clothing/eye protection/face protection                                                        |
| P281           | use personal protective equipment as required                                                                                    |
| P301+P330+P331 | IF SWALLOWED: rinse mouth, do NOT induce vomiting                                                                                |
| P302+P352      | IF ON SKIN: wash with soap and water                                                                                             |
| P304+P340      | IF INHALED: remove victim to fresh air and keep at rest in a position comfortable for breathing                                  |
| P305+P351+P338 | IF IN EYES: rinse continuously with water for several minutes, remove contact lenses if present and easy to do, continue rinsing |
| P308+P313      | IF EXPOSED OR CONCERNED: get medical advice/attention                                                                            |
| P310           | immediately call the ETH Emergency Desk: +41 44 342 11 88 (from mobile) or 888 (from landline)                                   |
| P311           | call the ETH Emergency Desk: +41 44 342 11 88 (from mobile) or 888 (from landline)                                               |
| P314           | get medical advice/attention if you feel unwell                                                                                  |
| P332+P313      | IF SKIN IRRITATION OCCURS: get medical advice/attention                                                                          |
| P337+P313      | IF EYE IRRITATION PERSISTS: get medical advice/attention                                                                         |
| P362           | take off contaminated clothing                                                                                                   |
| P403+P233      | store in a well ventilated place, keep container tightly closed                                                                  |
| P405           | store locked up                                                                                                                  |
| P501           | dispose of contents/container to [HCI-Shop](https://hci-shop.ethz.ch/en/)                                                        |

## Protective measures

### Gloves
[Occupational Safety and Health Act of 1970](https://www.osha.gov/sites/default/files/publications/osha3151.pdf) and [OSHA Glove Selection Chart](https://safety.fsu.edu/safety_manual/OSHA%20Glove%20Selection%20Chart.pdf) categorize gloves into four protection levels (very good, good, fair, poor (not recommended)) for given chemical. The levels of protection against chloroform for four types of gloves are:

- Neoprene: **good for limited service**.
- Natural latex or rubber: **poor (not recommended)**.
- Buthyl: **poor (not recommended)**.
- Nitrile: **poor (not recommended)**.

### Safety goggles
- Always wear safety goggles when handling the chemical. Corrective glasses are not considered safety googles.
- Handle the chemical inside the fume hood only (with exception of moving the closed bottle to and from the storage cabinet).

### Clothing
- Wear long trousers and fully covered shoes.
- Contact lenses are forbidden while working with chemical substances, even in combination with safety glasses.
- Do not wear cosmetics.
- Do not wear synthetic clothing while working with flammable liquids or gases or when a hazard is present as these materials tend to melt and stick to exposed skin.
- Do not wear headphones.

## Spill management
- Use personal protective equipment.
- Avoid dust formation, avoid breathing dust.
- Avoid breathing vapors or mist.
- Ensure adequate ventilation.
- Evacuate personnel to safe areas.
- Sweep up without creating dust and arrange disposal.
- Do not let it enter drain.
- If a spill happened outside the fume hood (on the floor or desktop) contact Dr Jakub Tkaczuk (+41 44 632 31 62) and the ETH Emergency Desk (+41 44 342 11 88 from mobile or 888 from landline).

[Back to chemical safety page](https://github.com/Global-Health-Engineering/group-safety/tree/main/02-chemical-safety)  
