---
title: "CHLOROBENZENE"
format: html
---

[← Back to Chemical Safety](../chemical-safety.qmd)


## Basic information
- Chemical formula(s): ${\rm C_6H_5Cl}$
- Other names: benzene chloride, chlorobenzol, phenyl chloride
- CAS: 108-90-7
- International Chemical Safety Card (ICSC): [0642](https://www.inchem.org/documents/icsc/icsc/eics0642.htm)
- Flammability: **yes - highly flammable**
- [NOAA's](https://cameochemicals.noaa.gov/chemical/2877) description: colourless to clear, yellowish liquid with a sweet almond-like odour, practically insoluble in water and somewhat denser than water; vapours heavier than air

## NFPA 704 (fire diamond)
- **Health (blue): 3** - short exposure could cause serious temporary or moderate residual injury.
- **Flammability (red): 3** - it can be ignited under almost all ambient temperature conditions. Its flash point is 29 °C. It's autoignition temperature is 592 °C.
- **Instability–reactivity (yellow): 0** - normally stable, even under fire exposure conditions, and is not reactive with water.
- **Special notice (white): -**

## Hazard statements
| Code | Phrase                                          |
| ---- | ----------------------------------------------- |
| H226 | flammable liquid and vapour                     |
| H302 | harmful if swallowed                            |
| H305 | may be harmful if swallowed and enters airways  |
| H315 | causes skin irritation                          |
| H332 | harmful if inhaled                              |
| H411 | toxic to aquatic life with long lasting effects |

## Precautionary statements
| Code           | Phrase                                                                                                            |
| -------------- | ----------------------------------------------------------------------------------------------------------------- |
| P210           | keep away from heat, hot surfaces, sparks, open flames and other ignition sources, no smoking                     |
| P233           | keep container tightly closed                                                                                     |
| P240           | ground and bond container and receiving equipment                                                                 |
| P241           | use explosion-proof electrical/ventilating/light/.../equipment                                                    |
| P242           | use only non-sparking tools                                                                                       |
| P243           | take precautionary measures to prevent static discharges                                                          |
| P261           | avoid breathing dust/fume/gas/mist/vapours/spray                                                                  |
| P264           | wash ... thoroughly after handling                                                                                |
| P271           | use only outdoors or in a well-ventilated area                                                                    |
| P273           | avoid release to the environment                                                                                  |
| P280           | wear protective gloves/protective clothing/eye protection/face protection                                         |
| P302+P352      | IF ON SKIN: wash with soap and water                                                                              |
| P303+P361+P353 | IF ON SKIN (or hair): remove/take off immediately all contaminated clothing, rinse skin with water or shower      |
| P304+P312      | IF INHALED: call the ETH Emergency Desk: +41 44 342 11 88 (from mobile) or 888 (from landline) if you feel unwell |
| P304+P340      | IF INHALED: remove victim to fresh air and keep at rest in a position comfortable for breathing                   |
| P312           | call the ETH Emergency Desk: +41 44 342 11 88 (from mobile) or 888 (from landline) if you feel unwell             |
| P321           | specific treatment (see the label)                                                                                |
| P332+P313      | IF SKIN IRRITATION OCCURS: get medical advice/attention                                                           |
| P362           | take off contaminated clothing                                                                                    |
| P370+P378      | IN CASE OF FIRE: use dry sand, dry chemical or alcohol-resistant foam to extinguish                               |
| P391           | collect spillage                                                                                                  |
| P403+P235      | store in a well ventilated place, keep cool                                                                       |
| P501           | dispose of contents/container to [HCI-Shop](https://hci-shop.ethz.ch/en/)                                         |

## Protective measures

### Gloves
[Occupational Safety and Health Act of 1970](https://www.osha.gov/sites/default/files/publications/osha3151.pdf) and [OSHA Glove Selection Chart](https://safety.fsu.edu/safety_manual/OSHA%20Glove%20Selection%20Chart.pdf) categorize gloves into four protection levels (very good, good, fair, poor (not recommended)) for given chemical. The levels of protection against chlorobenzene for four types of gloves are:

- Neoprene: **fair**.
- Natural latex or rubber: **poor (not recommended)**.
- Buthyl: **fair**.
- Nitrile: **poor (not recommended)**.

### Safety goggles
- Always wear safety goggles when handling chlorobenzene. Corrective glasses are not considered safety googles.
- Handle chlorobenzene inside the fume hood only (with exception of moving the closed bottle to and from the storage cabinet).

### Clothing
- Wear long trousers and fully covered shoes.
- Contact lenses are forbidden while working with chemical substances, even in combination with safety glasses.
- Do not wear cosmetics.
- Do not wear synthetic clothing while working with flammable liquids or gases or when a hazard is present as these materials tend to melt and stick to exposed skin.
- Do not wear headphones.

## Spill management
- Use personal protective equipment.
- Avoid dust formation, avoid breathing dust.
- Avoid breathing vapors or mist.
- Ensure adequate ventilation.
- Evacuate personnel to safe areas.
- Sweep up without creating dust and arrange disposal.
- Do not let it enter drain.
- If a spill happened outside the fume hood (on the floor or desktop) contact Dr Jakub Tkaczuk (+41 44 632 31 62) and the ETH Emergency Desk (+41 44 342 11 88 from mobile or 888 from landline).

[Back to chemical safety page](https://github.com/Global-Health-Engineering/group-safety/tree/main/02-chemical-safety)  
