---
title: "HYDROGEN CHLORIDE"
format: html
---

[← Back to Chemical Safety](../chemical-safety.qmd)


## Basic information
- Chemical formula(s): ${\rm HCl}$
- Other names: hydrogen chloride anhydrous, hydrochloric acid anhydrous
- CAS: 7647-01-0
- International Chemical Safety Card (ICSC): [0163](https://inchem.org/documents/icsc/icsc/eics0163.htm)
- Flammability: no
- [NOAA's](https://cameochemicals.noaa.gov/chemical/8731) description: colourless liquid/gas with a sharp, pungent odour, fumes strongly in moist air, corrosive to metals and tissues and irritating to the eyes and respiratory system, heavier than air.

## NFPA 704 (fire diamond)
- **Health (blue): 3** - short exposure could cause serious temporary or moderate residual injury.
- **Flammability (red): 0** - material will not burn under typical fire conditions, including intrinsically noncombustible materials such as concrete, stone, and sand. Material will not burn in air unless exposed to a temperature of 820 °C for more than 5 minutes.
- **Instability–reactivity (yellow): 1** - normally stable, but can become unstable at elevated temperatures and pressures.
- **Special notice (white):**
	- **ACID** - acid.

## Hazard statements
| Code | Phrase                                             |
| ---- | -------------------------------------------------- |
| H280 | contains gas under pressure: may explode if heated |
| H314 | causes severe skin burns and eye damage            |
| H331 | toxic if inhaled                                   | 

## Precautionary statements
| Code           | Phrase                                                                                                                           |
| -------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| P261           | avoid breathing dust/fume/gas/mist/vapours/spray                                                                                 |
| P280           | wear protective gloves/protective clothing/eye protection/face protection                                                        |
| P305+P351+P338 | IF IN EYES: rinse continuously with water for several minutes, remove contact lenses if present and easy to do, continue rinsing |
| P310           | immediately call the ETH Emergency Desk: +41 44 342 11 88 (from mobile) or 888 (from landline)                                   |
| P410+P403      | protect from sunlight, store in a well ventilated place                                                                          |

## Protective measures

### Gloves
[Occupational Safety and Health Act of 1970](https://www.osha.gov/sites/default/files/publications/osha3151.pdf) and [OSHA Glove Selection Chart](https://safety.fsu.edu/safety_manual/OSHA%20Glove%20Selection%20Chart.pdf) categorize gloves into four protection levels (very good, good, fair, poor (not recommended)) for given chemical. The levels of protection against hydrogen chloride for four types of gloves are:

- Neoprene: **very good**.
- Natural latex or rubber: **good**.
- Buthyl: **good**.
- Nitrile: **good**.

### Safety goggles
- Always wear safety goggles when handling hydrogen chloride. Corrective glasses are not considered safety googles.
- Handle hydrogen chloride inside the fume hood only (with exception of moving the closed bottle to and from the storage cabinet).

### Clothing
- Wear long trousers and fully covered shoes.
- Contact lenses are forbidden while working with chemical substances, even in combination with safety glasses.
- Do not wear cosmetics.
- Do not wear synthetic clothing while working with flammable liquids or gases or when a hazard is present as these materials tend to melt and stick to exposed skin.
- Do not wear headphones.

## Spill management
- Use personal protective equipment.
- Avoid dust formation, avoid breathing dust.
- Avoid breathing vapors or mist.
- Ensure adequate ventilation.
- Evacuate personnel to safe areas.
- Sweep up without creating dust and arrange disposal.
- Do not let it enter drain.
- If a spill happened outside the fume hood (on the floor or desktop) contact Dr Jakub Tkaczuk (+41 44 632 31 62) and the ETH Emergency Desk (+41 44 342 11 88 from mobile or 888 from landline).
