---
title: "MAGNESIUM CHLORIDE ANHYDROUS"
format: html
---

[← Back to Chemical Safety](../chemical-safety.qmd)


## Basic information
- Chemical formula(s): ${\rm MgCl_2}$
- Other names: magnesium chloride
- CAS: 7786-30-3
- International Chemical Safety Card (ICSC): [0764](https://inchem.org/documents/icsc/icsc/eics0764.htm)
- Flammability: no
- Description: colourless or white solid, highly soluble in water

## NFPA 704 (fire diamond)
- **Health (blue): 1** - exposure would cause irritation with only minor residual injury.
- **Flammability (red): 0** - will not burn under typical fire conditions, will not burn in air unless exposed to a temperature of 820 °C for more than 5 minutes.
- **Instability–reactivity (yellow): 0** - normally stable, even under fire exposure conditions, and is not reactive with water.
- **Special notice (white): -**

## Hazard statements
| Code | Phrase                           |
| ---- | -------------------------------- |
| H315 | causes skin irritation           | 
| H319 | causes serious eye irritation    |
| H335 | may cause respiratory irritation |

## Precautionary statements
| Code           | Phrase                                                                                                                           |
| -------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| P261           | avoid breathing dust/fume/gas/mist/vapours/spray                                                                                 |
| P264           | wash ... thoroughly after handling                                                                                               |
| P271           | use only outdoors or in a well-ventilated area                                                                                   |
| P280           | wear protective gloves/protective clothing/eye protection/face protection                                                        |
| P270           | do not eat, drink or smoke when using this product                                                                               |
| P321           | specific treatment (see the label)                                                                                               |
| P302+P352      | IF ON SKIN: wash with soap and water                                                                                             |
| P362+P364      | take off contaminated clothing and wash it before reuse                                                                          |
| P305+P351+P338 | IF IN EYES: rinse continuously with water for several minutes, remove contact lenses if present and easy to do, continue rinsing |
| P304+P340      | IF INHALED: remove victim to fresh air and keep at rest in a position comfortable for breathing                                  |
| P332+P313      | IF SKIN IRRITATION OCCURS: get medical advice/attention                                                                          |
| P337+P313      | IF EYE IRRITATION PERSISTS: get medical advice/attention                                                                         |
| P403+P233      | store in a well ventilated place, keep container tightly closed                                                                  |
| P405           | store locked up                                                                                                                  |
| P501           | dispose of contents/container to [HCI-Shop](https://hci-shop.ethz.ch/en/)                                                        |

## Protective measures

### Gloves
[Occupational Safety and Health Act of 1970](https://www.osha.gov/sites/default/files/publications/osha3151.pdf) and [OSHA Glove Selection Chart](https://safety.fsu.edu/safety_manual/OSHA%20Glove%20Selection%20Chart.pdf) do not provide recommendation on gloves for handling anhydrous magnesium chloride. [Gloves4U](https://www.gloves4u.eu/x/Chemical%20Resistant%20Chart%20-%20final%20(5).pdf) categorizes gloves into four protection levels (excellent, good, fair, poor (not recommended)) for given chemical. The levels of protection against anhydrous magnesium chloride for four types of gloves are:

- Neoprene: **good**.
- Natural latex or rubber: **excellent**.
- Buthyl: N/A
- Nitrile: **excellent**.

### Safety goggles
- Always wear safety goggles when handling anhydrous magnesium chloride. Corrective glasses are not considered safety googles.
- Handle anhydrous magnesium chloride inside the fume hood only (with exception of moving the closed bottle to and from the storage cabinet).

### Clothing
- Wear long trousers and fully covered shoes.
- Contact lenses are forbidden while working with chemical substances, even in combination with safety glasses.
- Do not wear cosmetics.
- Do not wear synthetic clothing while working with flammable liquids or gases or when a hazard is present as these materials tend to melt and stick to exposed skin.
- Do not wear headphones.

## Spill management
- Use personal protective equipment.
- Avoid dust formation, avoid breathing dust.
- Avoid breathing vapors or mist.
- Ensure adequate ventilation.
- Evacuate personnel to safe areas.
- Sweep up without creating dust and arrange disposal.
- Do not let it enter drain.
- If a spill happened outside the fume hood (on the floor or desktop) contact Dr Jakub Tkaczuk (+41 44 632 31 62) and the ETH Emergency Desk (+41 44 342 11 88 from mobile or 888 from landline).
