---
title: "OXYGEN GAS"
format: html
---

[← Back to Chemical Safety](../chemical-safety.qmd)


## Basic information
- Chemical formula(s): ${\rm O_2}$
- Other names: -
- CAS: 7782-41-7
- International Chemical Safety Card (ICSC): [0138](http://www.ilo.org/dyn/icsc/showcard.display?p_version=2&p_card_id=0138&p_lang=en)
- Flammability: no
- [NOAA's](https://cameochemicals.noaa.gov/chemical/8967) description: colourless, odourless, and tasteless gas; noncombustible, but actively supports the burning of combustible materials; some materials that don not burn in air burn in oxygen

## NFPA 704 (fire diamond)
- **Health (blue): 3** - short exposure could cause serious temporary or moderate residual injury.
- **Flammability (red): 0** - will not burn under typical fire conditions, will not burn in air unless exposed to a temperature of 820 °C for more than 5 minutes.
- **Instability–reactivity (yellow): 0** - normally stable, even under fire exposure conditions, and is not reactive with water.
- **Special notice (white):**
	- **OX** - oxidiser

## Hazard statements
| Code | Phrase                                              |
| ---- | --------------------------------------------------- |
| H270 | May cause or intensify fire; oxidiser of category 1 |
| H280 | contains gas under pressure; may explode if heated  |

## Precautionary statements
| Code      | Phrase                                                  |
| --------- | ------------------------------------------------------- |
| P220      | keep away from clothing and other combustible materials |
| P244      | keep valves and fittings free from oil and grease       |
| P370+P376 | IN CASE OF FIRE: stop leak if safe to do so             |
| P403      | store in a well-ventilated place                        |

## Protective measures

### Gloves
No skin protection necessary.

### Safety goggles
Always wear safety goggles when handling gaseous oxygen. Corrective glasses are not considered safety googles.

### Clothing
- Wear long trousers and fully covered shoes.
- Contact lenses are forbidden while working with chemical substances, even in combination with safety glasses.
- Do not wear cosmetics.
- Do not wear synthetic clothing while working with flammable liquids or gases or when a hazard is present as these materials tend to melt and stick to exposed skin.
- Do not wear headphones.

## Spill management
Not applicable.
