---
title: "TOLUENE"
format: html
---

[← Back to Chemical Safety](../chemical-safety.qmd)


## Basic information
- Chemical formula(s): ${\rm C_7H_8}$, ${\rm C_6H_5CH_3}$
- Other names: methylbenzene, toluol, phenylmethane
- CAS: 108-88-3
- International Chemical Safety Card (ICSC): [0078](https://www.inchem.org/documents/icsc/icsc/eics0078.htm)
- Flammability: **yes - highly flammable**
- [NOAA's](https://cameochemicals.noaa.gov/chemical/4654) description: clear colourless liquid with a characteristic aromatic odour, less dense than water and insoluble in water, hence floats on water; vapours heavier than air; may be toxic by inhalation, ingestion or skin contact

## NFPA 704 (fire diamond)
- **Health (blue): 2** - intense or continued but not chronic exposure could cause temporary incapacitation or possible residual injury.
- **Flammability (red): 3** - it can be ignited under almost all ambient temperature conditions. Its flash point is 4 °C. It's autoignition temperature is 480 °C.
- **Instability–reactivity (yellow): 0** - normally stable, even under fire exposure conditions, and is not reactive with water.
- **Special notice (white): -**

## Hazard statements
| Code  | Phrase                                                            |
| ----- | ----------------------------------------------------------------- |
| H225  | highly flammable liquid and vapour                                |
| H304  | may be fatal if swallowed and enters airways                      |
| H315  | causes skin irritation                                            |
| H336  | may cause drowsiness or dizziness                                 |
| H361d | suspected of damaging the unborn child                            |
| H373  | may cause damage to organs through prolonged or repeated exposure |

## Precautionary statements
| Code      | Phrase                                                                                                       |
| --------- | ------------------------------------------------------------------------------------------------------------ |
| P210      | keep away from heat, hot surfaces, sparks, open flames and other ignition sources, no smoking                |
| P240      | ground and bond container and receiving equipment                                                            |
| P301+P310 | IF SWALLOWED: immediately call the ETH Emergency Desk: +41 44 342 11 88 (from mobile) or 888 (from landline) |
| P302+P352 | IF ON SKIN: wash with soap and water                                                                         |
| P308+P313 | IF EXPOSED OR CONCERNED: get medical advice/attention                                                        |
| P314      | get medical advice/attention if you feel unwell                                                              |
| P403+P233 | store in a well ventilated place, keep container tightly closed                                              |

## Protective measures

### Gloves
[Occupational Safety and Health Act of 1970](https://www.osha.gov/sites/default/files/publications/osha3151.pdf) and [OSHA Glove Selection Chart](https://safety.fsu.edu/safety_manual/OSHA%20Glove%20Selection%20Chart.pdf) categorize gloves into four protection levels (very good, good, fair, poor (not recommended)) for given chemical. The levels of protection against toluene for four types of gloves are:

- Neoprene: **fair for limited service**.
- Natural latex or rubber: **poor (not recommended)**.
- Buthyl: **poor (not recommended)**.
- Nitrile: **fair for limited service**.

### Safety goggles
- Always wear safety goggles when handling toluene. Corrective glasses are not considered safety googles.
- Handle toluene inside the fume hood only (with exception of moving the closed bottle to and from the storage cabinet).

### Clothing
- Wear long trousers and fully covered shoes.
- Contact lenses are forbidden while working with chemical substances, even in combination with safety glasses.
- Do not wear cosmetics.
- Do not wear synthetic clothing while working with flammable liquids or gases or when a hazard is present as these materials tend to melt and stick to exposed skin.
- Do not wear headphones.

## Spill management
- Use personal protective equipment.
- Avoid dust formation, avoid breathing dust.
- Avoid breathing vapors or mist.
- Ensure adequate ventilation.
- Evacuate personnel to safe areas.
- Sweep up without creating dust and arrange disposal.
- Do not let it enter drain.
- If a spill happened outside the fume hood (on the floor or desktop) contact Dr Jakub Tkaczuk (+41 44 632 31 62) and the ETH Emergency Desk (+41 44 342 11 88 from mobile or 888 from landline).

[Back to chemical safety page](https://github.com/Global-Health-Engineering/group-safety/tree/main/02-chemical-safety)  
