---
title: "Appendix 1: Project List"
format: html
---

[← Back to Operational Safety](../operational-safety.qmd)

| Project/Activity               | Person responsible | Personnel involved |  Materials and chemicals used  | Machines and devices used                | Rooms             | Begin      | End        |
| ------------------------------ | ------------------ | ------------------ | ------------------------------ | ---------------------------------------- | ----------------- | ---------- | ---------- |
| Biogas sensor development      | Dr. Jakub Tkaczuk  | Gian Teufen, Mario Loeliger, Michele Strzelecki | SLA resin, CH4, CO2, IPA | 3D printer[^1], fume hood, MFC[^2]       | CLA B2.1, B2.2, J26 | 04-03-2024 | 30-06-2024 |
| Cookstove sensor development   | Dr. Jakub Tkaczuk  | Louis Ambuehl      | SLA resin, CH4, IPA         | 3D printer[^1], fume hood, Bunsen burner | CLA B2.2, J26 | 04-03-2024 | 30-06-2024 |
| Biogas sensor development V2   | Dr. Jakub Tkaczuk  | Mario Loeliger, Turlan Kuzhagaliyev | SLA resin, CH4, CO2, IPA | 3D printer[^1], fume hood, MFC[^2]       | CLA B2.1, B2.2, J26 | 08-07-2024 | 31-10-2024 |
| Biogas sensor container production | Dr. Jakub Tkaczuk | Salomon Ziegler | SLA resin, IPA                 | 3D printer[^1], laser cutter[^3]         | CLA B2.1, B2.2     | 29-07-2024 | 15-09-2024 |
| Biogas sensor development V3   | Dr. Jakub Tkaczuk  | Elia Weber         | SLA resin, CH4, CO2, IPA | 3D printer[^1], fume hood, MFC[^2]       | CLA B2.1, B2.2, J26 | 16-09-2024 | 31-03-2025 |
| Mycelia feces degradation      | Prof. Dr. Elizabeth Tilley | Jules Peter | acids, bases, microorganisms, feces, growth media | BSL2 safety cabinet, centrifuge, incubators, fume hood, fridge, freezer | CLA J26 | 15-09-2024 | 31-12-2025 |


[^1]: SLA 3D printer Formlabs 3 + Isopropanol washing station + UV curing station; located in CLA B2.2
[^2]: Bronkhorst Mass Flow Controllers FLEXIFLOW
[^3]: Laser cutter Epilog Fusion M2; located in CLA B2.1