---
title: "Appendix 2: List of Employees SAMV"
format: html
---

[← Back to Biological Safety](../biological-safety.qmd)


| Name        | Biological organisms | Risk group | Activity start | Activity end | Medical policies | Heath dossier |
| ----------- | -------------------- | ---------- | -------------- | ------------ | ---------------- | ------------- |
| Jules Peter | Coliforms            | 2          | 2024 Sep 15    | 2025 Dec 31  | Asura insurance  | -             |


Microorganisms are classified into four Risk Groups, and biological laboratories are classified into four corresponding Safety Levels:

| Risk level               | 1          | 2                         | 3                         | 4                   |
| ------------------------ | ---------- | ------------------------- | ------------------------- | ------------------- |
| Safety level             | 1          | 2                         | 3                         | 4                   |
| Permitted at GHE         | Yes        | Yes                       | No                        | No                  |
| Description of organisms | Do not cause disease in health human adults | Can cause disease in humans, but the disease is treatable or preventable | Cause serious disease in humans; treatments and vaccines for these diseases may exist | Cause deadly disease in humans, can easily travel from one person to another; no treatments or vaccines exist |
| Typical work area        | Open bench | Class 2 biosafety cabinet | Class 3 biosafety cabinet | Full isolation suit |
| Examples                 | E. coli K-12, S. cerevisiae (yeast), Lactobacillus, B. subtilis | Streptococcus, Herpes virus, most mammalian cell lines | Yersinia pestis (black plague), HIV, SARS virus | Ebola virus, Marburg virus, Lassa virus |