---
title: "Appendix 4: Emergency Planning and Procedures"
format: html
---

[← Back to Biological Safety](../biological-safety.qmd)


## Table of contents

1. [General rules on procedures for incidents](#general)
2. [Minor incidents and emergencies](#actions)
3. [Emergency telephone numbers display](#numbers)
4. [Emergency planning](#planning)
	1. [Spillage of infectious material WITHOUT aerosol formation](#planning_i)
	2. [Spillage of infectious material WITH aerosol formation](#planning_ii)
	3. [Injuries](#planning_iii)
	4. [Fire, explosion](#planning_iv)
	5. [Flooding, inundation](#planning_v)


## <a name="general"></a>1. General rules on procedures for incidents

As a basic rule, the notices in laboratories and other premises regarding escape routes, fire-fighting equipment and manual alarm buttons must be followed.


## <a name="actions"></a>2. Minor incidents and emergencies

Minor incidents are, in general, to be dealt with by the person(s) who caused them, if appropriate with the assistance of the Biosafety Officers (BSO).

In the event of a serious incident, the emergency services (internal / external) must be alerted. In emergency, the response should always follow the same pattern and proceed in a linear way:

| Step                   | Action for minor incident                                                     | Action in emergency                                               |
|----------------------- | ----------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| 1.&nbsp;Keep&nbsp;calm | Get an overall view of the situation                                          | Leave the danger zone in case of aerosol formation, fire, etc.    |
| 2. Alarm               | Inform BSO                                                                    | Alert the emergency services (internal / external)                |
| 3. Secure              | Confine the contaminated area                                                 | Rescue (self-protection)                                          |
| 4. Act                 | Disinfect or decontaminate according to the [hygiene plan](12_hygene_plan.md) | Extinguish, shut down power, close valves, etc. (self-protection) |


## <a name="numbers"></a>3. Emergency telephone numbers display

Emergency telephone numbers for external emergency services and in-house persons responsible for safety are available on stickers in the laboratories next to the telephones and by the first-aid boxes.

These phone numbers are also listed in [Appendix 3](03_emergency_telephone_numbers_and_contacts_for_safety.md).


## <a name="planning"></a>4. Emergency planning


### <a name="planning_i"></a>4.i Spillage of infectious material WITHOUT aerosol formation

| Step      | Action |
| --------- | ------ |
| 1. Alarm  | Alert BSO (+41 44 632 31 62)<br>**WHERE** did the incident occur?<br>**WHAT** WAS SPILLED/released?<br>**HOW MANY** people are affected?<br>**WHO** calls? |
| 2. Secure | Do not leave the affected area if it is safe to stay<br>Keep calm<br>Confine the contaminated area<br>Disinfect or decontaminate according to the [hygiene plan](12_hygene_plan.md)<br>Get clearance from BSO |
| 3. Act    | Complete the report sheet for laboratory incidents |


### <a name="planning_ii"></a>4.ii Spillage of infectious material WITH aerosol formation

| Step                        | Action |
| --------------------------- | ------ |
| 1. Evacuate the danger zone | **Immediately evacuate all the people from the danger zone**<br>Affected employees should decontaminate themselves immediately, if possible; otherwise, they should remain separated from the crowd to prevent spreading the dangerous substances |
| 2. Alarm                    | Alert BSO (+41 44 632 31 62)<br>**WHERE** did the incident occur?<br>**WHAT** WAS SPILLED/released?<br>**HOW MANY** people are affected?<br>**WHO** calls? |
| 3. Secure                   | Seal off the room, switch off ventilation, wait 30 minutes<br>decontaminate people<br>disinfect the room as instructed by the laboratory manager according to the [hygiene plan](12_hygene_plan.md)<br>disinfect contaminated equipment<br>issue clearance after checking that everything has been decontaminated |
| 4. Act                      | Complete the report sheet for laboratory incidents |


### <a name="planning_iii"></a>4.iii Injuries
[*See the poster: Emergencies in the lab - what to do?*](https://ethz.ch/content/dam/ethz/associates/services/Service/sicherheit-gesundheit-umwelt/files/laborsicherheit_neu/en/emergencies_in_the_lab-what_to_do.pdf)

| Step     | Action |
| -------- | ------ |
| 1. Alarm | Alert ETH Emergency Desk (+41 44 342 11 88 or 888)<br>Call the ambulance if necessary (144)<br>**WHERE** did the incident occur?<br>**WHAT** WAS SPILLED/released?<br>**HOW MANY** people are affected?<br>**WHO** calls? |
| 2. Act   | provide first aid<br>remove gloves and lab coat<br>wash hands and injured areas of the skin<br>disinfect with hand disinfectand or 70% ethanol<br>complete the report sheet for laboratory incidents<br> |


### <a name="planning_iv"></a>4.iv Fire, explosion

| Step                                                       | Action |
| ---------------------------------------------------------- | ------ |
| 1. Alarm (if the fire alarm did not set off automatically) | Alert ETH Emergency Desk (+41 44 342 11 88 or 888)<br>Call the fire brigade if necessary (118)<br>Alarm BSO (+41 44 632 31 62)<br>**WHERE** did the incident occur?<br>**WHAT** WAS SPILLED/released?<br>**HOW MANY** people are affected?<br>**WHO** calls? |
| 2. Rescue                                                  | Evacuate all people from the danger zone to the assembly area via the designated escape routes |
| 3. Act                                                     | Fight the fire (self-protection!)<br>Complete the report sheet for laboratory incidents |


### <a name="planning_v"></a>4.v Flooding, inundation

| Step      | Action |
| --------- | ------ |
| 1. Alarm  | Alert ETH Emergency Desk (+41 44 342 11 88 or 888)<br>Alarm BSO (+41 44 632 31 62)<br>**WHERE** did the incident occur?<br>**WHAT** WAS SPILLED/released?<br>**HOW MANY** people are affected?<br>**WHO** calls? |
| 2. Secure | Protect material and equipment<br>Shut off the supply lines<br>Clean and decontaminate surfaces<br>Decontaminate the waste water installation |
| 3. Act    | Complete the report sheet for laboratory incidents |
