---
title: "Appendix 9: SOPs"
format: html
---

[← Back to Biological Safety](../biological-safety.qmd)


The work in the laboratory is only permitted after familiarizing oneself with the following:
- [User manuals](https://drive.google.com/drive/folders/1-gGl0Jj20gXjfeDVtdbEAdviQkH1oo-P?usp=drive_link) for the wet laboratory equipment.
- [Rules, hazards, and precautions](../../02-chemical-safety/README.md) for chemicals available in the lab are described in the separate section of this safety concept.
- Standard Operating Procedures for experiments involving biological organisms will be developed for each planned experiment and will be available below.
- Process guides for some experiments conducted in the lab are provided [here](https://drive.google.com/drive/folders/1gTSVTPXE1Uu6BYCSFkvb-adi6UVNAWKj?usp=sharing).

## Standard Operating Procedures

### Biogas measurements

Biogas is a humid mixture of methane and carbon dioxide; with additional components being hydrogen sulphide, hydrogen, nitrogen, oxygen, carbon monoxide, and ammonia. In the laboratory experiments, it is being mimicked with pure methane and pure carbon dioxide.

The flow of both gases is regulated with Bronkhorst Flexiflow mass flow controllers. 

Humidity is regulated with two manual valves, splitting the flow so part of it passes through water bath.

Methane is hazardous because it is extremely flammable and it acts as a simple asphyxiant. Rapidly expanding gas may cause frostbites (Joule-Thomson effect). More information about methane are found [here](https://github.com/Global-Health-Engineering/group-safety/blob/main/02-chemical-safety/chemicals/METHANE_74-82-8.md).

Carbon dioxide is hazardous because it is heavier than air and can accumulate in lower parts of closed spaces risking suffocation in inhalation is prolonged. The laboratory is equipped with a CO_2 safety sensor and a shut-off valve on the CO_2 bottle. If CO_2 concentration rises above 1\%, a warning is triggered and the CLA services are informed the gas supply is shut; if it raises above 2\%, alarm is triggered and the CLA services are informed. More information about carbon dioxide can be found [here](https://github.com/Global-Health-Engineering/group-safety/blob/main/02-chemical-safety/chemicals/CARBON_DIOXIDE_124-38-9.md).

The experimental procedure for work with methane and carbon dioxide is as follows:
1. Know placement of the fire extinguisher and the fire blanket (outside the lab, to the right).
2. Familiarize yourself with the CO2 display placement. Once the CO2 alarm is triggered, leave the lab immediately and wait outside the lab in the corridor for arrival of the building safety team. You can mute the alarm with a red button just outside the lab door (the alarm is mutted, cannot switched off).
3. Experiments with methane and carbon dioxide can be performed only inside the fume hood with the sliding door open to normal operating mode. Only in this mode, the circulation of air inside the fume hood is sufficient and the conditions are safe for operation, preventing the gases to flow outside the fume hood.
4. Before starting the measurements, always turn on the methane sensor installed in the fume hood. Once the alarm goes off, shut down the methane supply and inform Jakub Tkaczuk.
4. The senors should be connected to the outlet line, minimizing the risk of CH_4 or CO_2 excaping the fume hood.
5. Dr. Jakub Tkaczuk is responsible for connecting CH_4 and CO_2 bottles to the system. Do not connect them yourself. The gas cabinet with CH_4 and CO_2 bottles needs to be closed properly (handle pointing downwards).
6. Connect your test setup to gas supply and to the outlet.
7. Open the gas on/off valves first.
8. Use the regulator valves on the safety cabinet to control the gas flow.
9. Prevent unwanted pressure increase in closed containers; check for pressure valuve with pressure indicator on the fume hood.
10. After use, close the supply valve on the safety cabinet and the regulating valve. Hand tight is good enough, prevent over-tightening the knobs.
11. Before leaving the lab, double check whether both valves on the fume hood are closed. There is no need for closing the valve on the gas bottle.
12. It is forbidden to eat, smoke, and use open fire in the lab.
13. It is forbidden to open windows and work with open door.
14. Glasses are mandatory for everyone in the room, when experiments with gasses are under way.
8.	Do not wear synthetic clothing; they melt and stick to exposed skin when on fire.
9.	Do not wear headphones, do not listen to music to be able to hear gas leaks.
11.	In case of emergency: inform the ETH mobile emergency contact from your mobile phone (+41 44 342 11 88) or from the phone next to the safety station on the corridor (888).
12.	Work with methane and carbon dioxide is permitted with one additional person in the lab.
