---
title: "Appendix 10: Use of Class 2 Cabinets"
format: html
---

[← Back to Biological Safety](../biological-safety.html)


## General information

Class 2 safety cabinets ensure that people, products, and the environment are protected. Around 70% of the air flow is recirculated in the compartment of the biosafety cabinet. The remaining 30% is discharged into the surrounding through the high-performance HEPA filters. This 30% flow is continuously extracted from the laboratory, contributing to occupational safety and the protection of health.

Good microbiological practices (GMP) are essential outside and **inside** the safety cabinet, since they protect only against aerosol contamination and not against contact contamination. Therefore, the employee's hands must remain inside the cabinet during work and must not be brought up to the face.

## Hazards for people and the environment

The primary danger of releasing a biological substance from the biosafety cabinet results from incorrect operating procedures. Therefore, it is particularly important to familiarize oneself with the operational procedure and follow the basic safety rules described in the next section.

## Precautions and rules of conduct

- Avoid air currents in the working area. Keep windows and doors closed during work in the safety cabinet, open and close the door to the laboratory slowly.
- Switch on the equipment approximately 10 to 30 minutes before starting your work. Only work in the cabinet with the *GMP mode*, do not use the *Eco mode*.
- All zones need to be green in normal operation, if they are not, filtering does not work properly.
- Use personal protective equipment, a laboratory coat, gloves, and glasses.
- Prevent aerosol formation as far as possible, even under the safety cabinet.
- Do not disturb the laminar air flow in the cabinet:
    - no rapid or violent movements;
    - bring bulky equipment into the safety cabinet only if absolutely essential. Do it in the *cleaning mode* before starting your work, take it out in the *cleaning mode* after finishing your work.
    - do not store any unnecessary items in the safety cabinet;
    - do not use Bunsen burners over extended periods, only ignite as required, using a sensor or foot switch;
    - do not cover air holes.
- All equipment brought into the safety cabinet must be cleaned and disinfected beforehand. Items of equipment removed from the safety cabinet must be disinfected and cleaned if necessary (in this order).
- The working surface of the safety cabinet must be cleaned and disinfected at the end of the work. Waste must be disposed of, Pasteur pipettes on hoses must be removed and vacuum hoses must be disinfected (see operating instructions on hygiene and waste disposal). If flammable disinfectants are stipulated, disinfect only by wiping with quantities of less than 20 ml in order to prevent explosion. **However, the flow in biosafety cabinet will cause alcohol evaporation** and degrade the disinfecting capacity, therefore larger volume may be necessary to disinfect working cabinet after use.
- If work is not being carried out under the safety cabinet, it should be switched to stand-by mode in order to save energy. Night mode can be switched on if the hood needs to be left over night and the work shall continue the following day.
- If work involving potentially hazardous biological substances has been carried out, the equipment must be switched off only by an authorized person. The sterility of the inside should be monitored from time to time by placing open Petri dishes lined with nutrients there. If microorganism growth occurs on the nutrients, the Laboratory Manager and the responsible person must be informed in accordance with the service plan.

## Malfunctions and dangers

Safe operation is only possible if the window sash is in a correct position and the display marks all zones as green. Never ignore alarm signals.
The cabinet does not offer any protection against harmful gases and vapours.
- In the event of a complete functional failure during work with potentially dangerous biological substances work must be stopped in a controlled manner. The laboratory manager and the BSO of the group must be informed immediately.
- In the event of a visual and acoustic alarm, the cause of the malfunction must be identified, if necessary, with the help of the operating instructions and, if possible, corrected by the operator themselves. If it is not possible to correct the malfunction or if attempts are unsuccessful, the responsible person must be notified in accordance with the service plan. The most probable causes of alarms are:
    - obstructed flow - remove any items from the air intake;
    - incorrect windows sash position for given operational mode - check the position and the mode;
    - incorrect operational mode for given window sash position - check the position and the mode;
    - turbulent flow - wait until the system reestablishes correct mass flow and move slower so the contaminated air does not leave the cabinet.
- If there is an indication that the preliminary filter or the HEPA filter needs to be replaced:
    - alarm signal without warning - work shall be continued and the responsible person must be notified in accordance with the service plan, so the new filters can be ordered  and changed.
    - alarm signal with warning - work must be ended in a controlled manner and the responsible person must be notified in accordance with the service plan, so the new filters can be ordered and changed.

## Tests, maintenance, and disposal

Servicing and repair work must only be carried out with the permission of the Laboratory Manager and must normally be performed by the manufacturer. The safety cabinet must be checked annually by a specialist. For maintenance, only replacement parts matching the original parts in terms of material and design may be used.

## Accidents and first aid

If a person is wounded while working in the biosafety cabinet, rinse an open wound, allow it to bleed, if possible, and spray it immediately with disinfectant. Apply more disinfectant, if necessary, and allow it to act according to the instructions, though at least for 30 minutes.

If necessary, alert the ETH first-aid team (internal phone number: 888) or the ambulance (144). Pay attention to Emergency planning: action in the event of incidents in the laboratory. Complete the report sheet for laboratory incidents, inform laboratory manager and BSO.


