---
title: "Appendix 4: Collection of Operating Instructions, User Manuals, and SOPs"
format: html
---

[← Back to Operational Safety](../operational-safety.qmd)

# Collection of operating instructions, user manuals, and SOP
The work in the workshops is only permitted after training and familiarizing oneself with:

- the list of chemicals available in the workshop (see the section below).
- SOPs from this document.  
- [user manuals](https://drive.google.com/drive/folders/1W3yf1Jw-kGBAyeiPq0gCCjTKWzRRx1iA?usp=sharing) for all the workshop equipment.

## Rules, hazards, and precautions for chemicals
The chemicals available in the GHE workshop are:

- Loctite
- WD-40
- Gorilla glue for wood
- Silicon
- Epoxy resin
- Isopropanol
- Acetone

## Standard Operating Procedures
- [CNC milling machine (Mekanika Pro Education Pack)](04_SOPs/Mekanika_CNC.qmd)
- [Drill (DeWalt)](04_SOPs/DeWalt_handheld_drill.qmd)
- [Drill Press](04_SOPs/ProMac_drill_press.qmd)
- [Injection molding machine (HoliPress 38)](04_SOPs/HoliPress_injection_molding.qmd)
- [Jigsaw (DeWalt)](04_SOPs/DeWalt_jigsaw.qmd)
- [Laser Cutter (Trotec Q400)](04_SOPs/Trotec_laser_cutter.qmd)
- [Orbital Sander (DeWalt)](04_SOPs/DeWalt_orbital_sander.qmd)
- [Router (DeWalt)](04_SOPs/DeWalt_router.qmd)