---
title: "Appendix 5: Laboratory and Workshop Rules"
format: html
---

[← Back to Operational Safety](../operational-safety.qmd)

# Laboratory and workshop rules

## Emergency
- The ETH Emergency number is **+41 44 342 11 88** from mobile devices, save this number in your contacts. If you call from the ETH stationary phone, dial **888**. All emergencies and accidents must be reported as soon as possible.
- The nearest First Aid Rooms are located in CLA E 2, ML F 32.2.
- In case of a serious emergency follow the [Emergency plan](../../03-biological-safety/appendices/04_emergency_planning_and_procedures.md) and the emergency poster. Safety-relevant lab incidents are reported to the Group Safety Representative and SSHE.
- Principle to be followed in an emergency situation: look - think - act.

## General
- No foods and drinks are permitted (neither eating nor storing).
- Use proper storage containers.
- Find locations of the laboratory safety showers, eyewash stations, and fire extinguishers.
- Facilities must be be kept clean and orderly. Only the actually needed devices and materials shall be kept on the workbenches. Supplies are kept in the designated areas or in the cupboards.
- Doors and windows are kept shut while working. In the laboratory, when the fume hood or the biological cabinet are operating, the windows have to remain closed.

## Entry
- Every lab user needs to complete the "Safety in the laboratory" test before entering the lab for the first time. The screenshot of the results needs to be sent to [Jakub Tkaczuk](mailto:jtkaczuk@ethz.ch).
- Bachelor's and Master's students are not allowed to work alone in the lab.
- Children are not permitted in neither the laboratory nor the workshop.

## Clothing
- Hair needs to be tied up, never work with long loose hair.
- Do not wear jewelry in the laboratory.
- Cosmetics must not be used when working in the laboratory. 
- Wear long trousers (stockings and leggings are not considered long trousers) and fully covered shoes (Bare feet, open-toe shoes, sandals, and high heels are not permitted).
- Contact lenses are forbidden while working with chemical substances in the lab (the natural reflex to clamp the eyelids shut makes it hard, if not impossible, to remove the contamination in the event of an eye injury from splattering). Contact lenses are forbidden even in combination with safety glasses.
- Do not wear synthetic clothing while working with flammable liquids or gases or when a hazard is present as these materials tend to melt and stick to exposed skin.
- Storing and using personal items, e.g., bags, mobile phone, should be minimized in the work area.

## Personal Protective Equipment (PPE)
- When one person uses chemicals, heat, or glass equipment, all persons in the lab must wear lab coats and safety googles.
- Lab coat must be worn when working in a lab in which chemical or biological materials are handled. The lab coat is buttoned up.
- Gloves must be worn for any activity involving risk (hand contamination or injury), e.g., when handling harmful chemicals or dealing with high temperatures. If your experiment requires gloves, make sure to select the proper type of gloves based on the information provided for [each chemical](../../02-chemical-safety/README.md). Contaminated gloves must be immediately replaced or cleaned. When using gloves, care should be taken not to transfer any metal powders or chemicals when using phones, opening doors, using water faucets, etc. Remove gloves beforehand.
- Never leave the laboratory wearing gloves, safety glasses, or the lab coat.
- Depending on the hazards, additional PPE may be necessary for particular task, e.g., hearing protection, safety shoes, dust mask, gloves protecting against low or high temperatures, etc.
- Defective and expired PPE must be replaced and may not be used.

## Experimental work & machining
- If there is any part of an experiment you do not understand, you should pause and ask the assistant/responsible person before continuing.
- Assume that all chemicals of unknown toxicity are highly toxic.
- Combine reagents in their appropriate order, such as adding acid to water.
- Avoid adding solids to hot liquids.
- All lab chemicals are labeled, kept in suitable receptacles and never left open, except when actually using them.
- Put the chemicals back in their respective safety cabinets after finishing the experiments.
- Do not use the fume hood for evaporation and disposal of volatile solvents.
- No headphones or ear buds are allowed during experimental operations.
- Syringes and needles can only be used when justified. After use, they must be disposed of in the sharp disposal box.
- Before handling the chemicals and before working with machines and equipment, every employee must be instructed/trained according to the workplace conditions and their previous knowledge. Work on certain machines, e.g., lathe, may only be performed by persons with appropriate training, e.g., mechanics with federal certificate of competence.
- Before handling hazardous chemical substances and before carrying out experiments in which a hazardous substance could possibly be released, the risk potential must be determined and the necessary precautions taken. For activities with hazardous chemicals, the precautions described in the respective safety datasheets must be heeded and the rules of conduct for handling such substances must be specified in the individual user instructions and the Standard Operating Procedures (SOP).
- Pregnant and breastfeeding women may not handle metal powders nor lab chemicals. Exceptions are regulated in the Maternity Protection Ordinance. A risk analysis must be made according to [ETH information sheet: Maternity protection](https://ethz.ch/content/dam/ethz/associates/services/Service/sicherheit-gesundheit-umwelt/files/mutterschutz/en/Maternity_protection-factsheet.pdf).
- Work with malodorous or toxic substances and highly flammable gases may only be performed inside the fume hood. The necessary protective measures must be taken into consideration.

## Cleaning and storage
- ETH cleaning personnel is only responsible for cleaning the floor and empty the trash bins.
- Work surfaces have to be decontaminated and cleaned regularly by the users. The surfaces need to be cleaned and decontaminated after the work is finished. Only a suitable agent can be used.
- Clean the workplace before leaving the laboratory.
- Combustible fluids requiring refrigeration for storage, extremely flammable, and highly flammable substances may only be stored in explosionproof refrigerators or cabinets.
- Pressurized gas cylinders are always secured with a chain to protect against falling or stored and fastened with a chain in a gas cabinet. They may only be transported with the transport trolley specifically intended for this purpose and for the bottle size.

## Hygiene and waste
- Do not touch your mouth and eyes during work. Wash hands thoroughly after working and before leaving the premises.
- Wash exposed areas of the skin prior to leaving the laboratory.
- Every user is responsible for proper waste disposal - do not pour chemicals down drains, do not dispose active biological waste in the general waste bin.
- Special waste must be collected according to the guidelines in the waste disposal concept.